version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  tests:
    image: node:22-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["npx", "playwright", "test"]
    depends_on:
      - app