name: Run UI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      app:
        image: expense-tracker-app
        ports:
          - "3000:3000"
        options: >-
          --health-cmd="curl -f http://localhost:3000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test